api:
  dashboard: true

entryPoints:
  websecure:
    address: ":443"

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: swiftkimani@gmail.com
      tlsChallenge: {}
      storage: /letsencrypt/acme.json
